runtime: python
env: flex
entrypoint: gunicorn -b :$PORT --timeout 60 bot.wsgi:application
skip_files:
  - /venv
  - .env

runtime_config:
  python_version: 3.6

manual_scaling:
  instances: 1

# env_variables:
