version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/python:3.6.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
  unittest:
    working_directory: ~
    docker:
      - image: circleci/python:3.6.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: pipenv run python -m unittest discover
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unittest:
          requires:
            - build
