version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/python:3.6.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run: 
          name: Run tests
          command: |
            pipenv run pylint --disable C0301,C0111,R0201,C0103,W0613,R0903 bot/
            pipenv run python -m unittest discover
